### ISSUE TITLE
TypeError: Cannot read property 'findByEmail' of undefined at UniqueEmailValidator.validate 

### ISSUE THREAD

**Issue by vanlanh10273** [hoangtm1601/nest-base#21]
Can you help me to review this issue?<img width="1002" alt="Screen Shot 2021-09-05 at 10 59 58 AM" src="https://user-images.githubusercontent.com/9089476/132114760-c0feb428-3ff9-431e-be63-6d684ad66def.png">

**Comment by hoangtm1601** [comment]
Seems that userService cannot be injected into uniqueEmailValidator decorator, check your module first or you can ignore this decorator on DTO class.

**Comment by vanlanh10273** [comment]
I was followed your source. I don't know why userService cannot inject to uniqueEmailValidator. How can I fix this?

**Comment by hoangtm1601** [comment]
Oh, sorry to hear that because this repository was created more than 1 year ago so some components are deprecated. I will take a look soon.
For the temporary solution, you can comment this line for continue testing. Feel free to contribute to this repo. Thank you
!
https://github.com/hoangtm1601/nest-base/blob/master/src/users/dto/create-user.dto.ts#L8

**Comment by vanlanh10273** [comment]
Okie, I'm waiting your help. I'm a newbie nestjs. :)

**Comment by hoangtm1601** [comment]
![Screenshot 2021-09-21 at 16 21 28](https://user-images.githubusercontent.com/43944930/134145892-860b4818-f926-4b21-8119-b36d851a65c5.png)
It currently works from my side with env:
- node 14
- npm 6.14
- mysql 5.8

**Comment by vanlanh10273** [comment]
My nestjs version is 8.1.1
Can you add my skype is vanlanh10273?

**Comment by hoangtm1601** [comment]
I think it's better to flow construction from Official docs. For your problem maybe you missed this configuration from class-validator on `main.ts`, so class-validator cannot inject UserService to your decorator class.
```
  useContainer(app.select(ValidatorModule), { fallbackOnErrors: true })
```

Refs: https://github.com/nestjs/nest/issues/528
Good luck!
